
# clear environment
rm(list=ls())

library(dplyr)
library(knitr)
library(xtable)
library(kableExtra)
library(foreign)
library(nnet)

RANDS1 <- read.csv("/Users/toriwhite/Downloads/RANDS1.csv")
RANDS2 <- read.csv("/Users/toriwhite/Downloads/RANDS2.csv")

RANDS.COVID1 <- read.csv("/Users/toriwhite/Downloads/RANDS_COVID_1.csv")
RANDS.COVID2 <- read.csv("/Users/toriwhite/Downloads/RANDS_COVID_2.csv")

atp <- read.spss("/Users/toriwhite/Downloads/W93_Jul21/ATP W93.sav", to.data.frame = TRUE)
na.omit(atp)
atp2 <- read.spss("/Users/toriwhite/Downloads/W72_Aug20/ATP W72.sav", to.data.frame = TRUE)
na.omit(atp2)


# Convert the columns to numeric if they are not already
RANDS1$AWEBOFNO_N <- as.integer(RANDS1$AWEBOFNO_N)
RANDS1$AWEBOFNO_F <- as.integer(RANDS1$AWEBOFNO_F)
RANDS1$MODNO_N <- as.integer(RANDS1$MODNO_N)
RANDS1$VIGNO_N <- as.integer(RANDS1$VIGNO_N)
RANDS1$ALC12MNO_N <- as.integer(RANDS1$ALC12MNO_N)

# Create a new data frame without rows containing NAs
RANDS1 <- RANDS1[complete.cases(RANDS1),]

RANDS1$AWEBOFNO_N[RANDS1$AWEBOFNO_F == 1] <- RANDS1$AWEBOFNO_N[RANDS1$AWEBOFNO_F == 1] * 7 # if the participant response was daily, then value was multiplied by 7 so all values have the same units

# LIGHT EXERCISE ADJUSTED VALUES
RANDS1$MODNO_N[RANDS1$AWEBOFNO_F == 1] <- RANDS1$MODNO_N[RANDS1$AWEBOFNO_F == 1] * 365
RANDS1$MODNO_N[RANDS1$AWEBOFNO_F == 2] <- RANDS1$MODNO_N[RANDS1$AWEBOFNO_F == 2] * 52
RANDS1$MODNO_N[RANDS1$AWEBOFNO_F == 3] <- RANDS1$MODNO_N[RANDS1$AWEBOFNO_F == 3] * 12

# GAINS ADJUSTED VALUES
RANDS1$STRNGO_N[RANDS1$STRNGO_F == 1] <- RANDS1$STRNGO_N[RANDS1$STRNGO_F == 1] * 365
RANDS1$STRNGO_N[RANDS1$STRNGO_F == 2] <- RANDS1$STRNGO_N[RANDS1$STRNGO_F == 2] * 52
RANDS1$STRNGO_N[RANDS1$STRNGO_F == 3] <- RANDS1$STRNGO_N[RANDS1$STRNGO_F == 3] * 12

# VIGOROUS EXERCISE ADJUSTED VALUES
RANDS1$VIGNO_N[RANDS1$VIGNO_F == 1] <- RANDS1$VIGNO_N[RANDS1$VIGNO_F == 1] * 365
RANDS1$VIGNO_N[RANDS1$VIGNO_F == 2] <- RANDS1$VIGNO_N[RANDS1$VIGNO_F == 2] * 52
RANDS1$VIGNO_N[RANDS1$VIGNO_F == 3] <- RANDS1$VIGNO_N[RANDS1$VIGNO_F == 3] * 12

## ALCOHOL INTAKE IN A YEAR ADJUSTED VALUES
RANDS1$ALC12MNO_N[RANDS1$ALC12MNO_F == 1] <- RANDS1$ALC12MNO_N[RANDS1$ALC12MNO_F == 1] * 365
RANDS1$ALC12MNO_N[RANDS1$ALC12MNO_F == 2] <- RANDS1$ALC12MNO_N[RANDS1$ALC12MNO_F == 2] * 52
RANDS1$ALC12MNO_N[RANDS1$ALC12MNO_F == 3] <- RANDS1$ALC12MNO_N[RANDS1$ALC12MNO_F == 3] * 12

RANDS1Regression <- lm(AWEBOFNO_N ~ ANX_1 + ANX_3 + MODNO_N +  STRNGNO_N + VIGNO_N + 
                         ALC12MNO_N + ACIWTHLS + ACISAD + ACIRSTLS + ACINERV + ACIHOPLS + 
                         ACIEFFRT, data = RANDS1)

summary(RANDS1Regression)



# Convert the columns to numeric if they are not already
RANDS2$AWEBOFNO_N <- as.integer(RANDS2$AWEBOFNO_N)
RANDS2$AWEBOFNO_F <- as.integer(RANDS2$AWEBOFNO_F)
RANDS2$MODNO_N <- as.integer(RANDS2$MODNO_N)
RANDS2$VIGNO_N <- as.integer(RANDS2$VIGNO_N)
RANDS2$ALC12MNO_N <- as.integer(RANDS2$ALC12MNO_N)


# Create a new data frame without rows containing NAs
RANDS2 <- RANDS2[complete.cases(RANDS2),]

RANDS2$AWEBOFNO_N[RANDS2$AWEBOFNO_F == 1] <- RANDS2$AWEBOFNO_N[RANDS2$AWEBOFNO_F == 1] * 7

RANDS2$MODNO_N[RANDS2$AWEBOFNO_F == 1] <- RANDS2$MODNO_N[RANDS2$AWEBOFNO_F == 1] * 365
RANDS2$MODNO_N[RANDS2$AWEBOFNO_F == 2] <- RANDS2$MODNO_N[RANDS2$AWEBOFNO_F == 2] * 52
RANDS2$MODNO_N[RANDS2$AWEBOFNO_F == 3] <- RANDS2$MODNO_N[RANDS2$AWEBOFNO_F == 3] * 12

# GAINS ADJUSTED VALUES
RANDS2$STRNGO_N[RANDS2$STRNGO_F == 1] <- RANDS2$STRNGO_N[RANDS2$STRNGO_F == 1] * 365
RANDS2$STRNGO_N[RANDS2$STRNGO_F == 2] <- RANDS2$STRNGO_N[RANDS2$STRNGO_F == 2] * 52
RANDS2$STRNGO_N[RANDS2$STRNGO_F == 3] <- RANDS2$STRNGO_N[RANDS2$STRNGO_F == 3] * 12

# VIGOROUS EXERCISE ADJUSTED VALUES
RANDS2$VIGNO_N[RANDS2$VIGNO_F == 1] <- RANDS2$VIGNO_N[RANDS2$VIGNO_F == 1] * 365
RANDS2$VIGNO_N[RANDS2$VIGNO_F == 2] <- RANDS2$VIGNO_N[RANDS2$VIGNO_F == 2] * 52
RANDS2$VIGNO_N[RANDS2$VIGNO_F == 3] <- RANDS2$VIGNO_N[RANDS2$VIGNO_F == 3] * 12

## ALCOHOL INTAKE IN A YEAR ADJUSTED VALUES
RANDS2$ALC12MNO_N[RANDS2$ALC12MNO_F == 1] <- RANDS2$ALC12MNO_N[RANDS2$ALC12MNO_F == 1] * 365
RANDS2$ALC12MNO_N[RANDS2$ALC12MNO_F == 2] <- RANDS2$ALC12MNO_N[RANDS2$ALC12MNO_F == 2] * 52
RANDS2$ALC12MNO_N[RANDS2$ALC12MNO_F == 3] <- RANDS2$ALC12MNO_N[RANDS2$ALC12MNO_F == 3] * 12

RANDS2Regression <- lm(AWEBOFNO_N ~ ANX_1 + ANX_3 + MODNO_N +  STRNGNO_N + 
                         VIGNO_N + ALC12MNO_N + ACIWTHLS + ACISAD + ACIRSTLS + 
                         ACINERV + ACIHOPLS + ACIEFFRT, data = RANDS2)
summary(RANDS2Regression)



# CREATING BINARY RESPONSE VARAIBLES TO TEST DIFFERENT LEVELS OF INTERNET USE
atpTEST <- mutate(atp,
                  A = if_else(atp$F_INTFREQ == "Refused", 1, 0),
                  B = if_else(atp$F_INTFREQ == "Less often", 1, 0),
                  C = if_else(atp$F_INTFREQ == "Several times a week", 1, 0),
                  D = if_else(atp$F_INTFREQ == "Almost constantly", 1, 0))

# ADJUSTING THE LENGTH OF atpTEST VARIALBES TO RUN A PROPER REGRESSION
ASubset <- atpTEST$A[1:length(RANDS.COVID1$ANXLEVEL)]
BSubset <- atpTEST$B[1:length(RANDS.COVID1$ANXLEVEL)]
CSubset <- atpTEST$C[1:length(RANDS.COVID1$ANXLEVEL)]
DSubset <- atpTEST$D[1:length(RANDS.COVID1$ANXLEVEL)]

# RUNNING REGRESSION USING DATA FROM BSubset & RANDS.COVID1
covidRegressionB <- lm(BSubset ~ RANDS.COVID1$ANXFREQ + RANDS.COVID1$ANXLEVEL + RANDS.COVID1$DEPFREQ + RANDS.COVID1$DEPLEVEL + RANDS.COVID1$SRHPSYCH)
summary(covidRegressionB)

# RUNNING REGRESSION USING DATA FROM CSubset & RANDS.COVID1
covidRegressionC <- lm(CSubset ~ RANDS.COVID1$ANXFREQ + RANDS.COVID1$ANXLEVEL + RANDS.COVID1$DEPFREQ + RANDS.COVID1$DEPLEVEL + RANDS.COVID1$SRHPSYCH)
summary(covidRegressionC)

# RUNNING REGRESSION USING DATA FROM DSubset & RANDS.COVID1
covidRegressionD <- lm(DSubset ~ RANDS.COVID1$ANXFREQ + RANDS.COVID1$ANXLEVEL + RANDS.COVID1$DEPFREQ + RANDS.COVID1$DEPLEVEL + RANDS.COVID1$SRHPSYCH)
summary(covidRegressionD)


# ADJUSTING THE LENGTH OF atpTEST VARIALBES TO RUN A PROPER REGRESSION
AASubset <- atpTEST$A[1:length(RANDS.COVID2$ANXLEVEL)]
BBSubset <- atpTEST$B[1:length(RANDS.COVID2$ANXLEVEL)]
CCSubset <- atpTEST$C[1:length(RANDS.COVID2$ANXLEVEL)]
DDSubset <- atpTEST$D[1:length(RANDS.COVID2$ANXLEVEL)]

# RUNNING REGRESSION USING DATA FROM AASubset & RANDS.COVID2
covidRegressionAA <- lm(AASubset ~ RANDS.COVID2$ANXFREQ + RANDS.COVID2$ANXLEVEL + RANDS.COVID2$DEPFREQ + RANDS.COVID2$DEPLEVEL)
summary(covidRegressionAA)

# RUNNING REGRESSION USING DATA FROM BBSubset & RANDS.COVID2
covidRegressionBB <- lm(BBSubset ~ RANDS.COVID2$ANXFREQ + RANDS.COVID2$ANXLEVEL + RANDS.COVID2$DEPFREQ + RANDS.COVID2$DEPLEVEL)
summary(covidRegressionBB)

# RUNNING REGRESSION USING DATA FROM CCSubset & RANDS.COVID2
covidRegressionCC <- lm(CCSubset ~ RANDS.COVID2$ANXFREQ + RANDS.COVID2$ANXLEVEL + RANDS.COVID2$DEPFREQ + RANDS.COVID2$DEPLEVEL)
summary(covidRegressionCC)

# RUNNING REGRESSION USING DATA FROM DDSubset & RANDS.COVID2
covidRegressionDD <- lm(DDSubset ~ RANDS.COVID2$ANXFREQ + RANDS.COVID2$ANXLEVEL + RANDS.COVID2$DEPFREQ + RANDS.COVID2$DEPLEVEL)
summary(covidRegressionDD)



# CREATING BINARY RESPONSE VARAIBLES TO TEST DIFFERENT LEVELS OF INTERNET USE
atpTEST2 <- mutate(atp2,
                   A = if_else(atp2$F_INTFREQ == "Refused", 1, 0),
                   B = if_else(atp2$F_INTFREQ == "Less often", 1, 0),
                   C = if_else(atp2$F_INTFREQ == "Several times a week", 1, 0),
                   D = if_else(atp2$F_INTFREQ == "Almost constantly", 1, 0))

# ADJUSTING THE LENGTH OF atpTEST2 VARIALBES TO RUN A PROPER REGRESSION
A2Subset <- atpTEST2$A[1:length(RANDS.COVID1$ANXLEVEL)]
B2Subset <- atpTEST2$B[1:length(RANDS.COVID1$ANXLEVEL)]
C2Subset <- atpTEST2$C[1:length(RANDS.COVID1$ANXLEVEL)]
D2Subset <- atpTEST2$D[1:length(RANDS.COVID1$ANXLEVEL)]

# RUNNING REGRESSION USING DATA FROM ASubset2 & RANDS.COVID1
covidRegressionA2 <- lm(A2Subset ~ RANDS.COVID1$ANXFREQ + RANDS.COVID1$ANXLEVEL + RANDS.COVID1$DEPFREQ + RANDS.COVID1$DEPLEVEL + RANDS.COVID1$SRHPSYCH)
summary(covidRegressionA2)

# RUNNING REGRESSION USING DATA FROM BSubset2 & RANDS.COVID1
covidRegressionB2 <- lm(B2Subset ~ RANDS.COVID1$ANXFREQ + RANDS.COVID1$ANXLEVEL + RANDS.COVID1$DEPFREQ + RANDS.COVID1$DEPLEVEL + RANDS.COVID1$SRHPSYCH)
summary(covidRegressionB2)

# RUNNING REGRESSION USING DATA FROM CSubset2 & RANDS.COVID1
covidRegressionC2 <- lm(C2Subset ~ RANDS.COVID1$ANXFREQ + RANDS.COVID1$ANXLEVEL + RANDS.COVID1$DEPFREQ + RANDS.COVID1$DEPLEVEL + RANDS.COVID1$SRHPSYCH)
summary(covidRegressionC2)

# RUNNING REGRESSION USING DATA FROM DSubset2 & RANDS.COVID1
covidRegressionD2 <- lm(D2Subset ~ RANDS.COVID1$ANXFREQ + RANDS.COVID1$ANXLEVEL + RANDS.COVID1$DEPFREQ + RANDS.COVID1$DEPLEVEL + RANDS.COVID1$SRHPSYCH)
summary(covidRegressionD2)

BB2Subset <- atpTEST2$B[1:length(RANDS.COVID2$ANXLEVEL)]
CC2Subset <- atpTEST2$C[1:length(RANDS.COVID2$ANXLEVEL)]
DD2Subset <- atpTEST2$D[1:length(RANDS.COVID2$ANXLEVEL)]

covidRegressionBB2 <- glm(BB2Subset ~ RANDS.COVID2$ANXFREQ + RANDS.COVID2$ANXLEVEL + RANDS.COVID2$DEPFREQ + RANDS.COVID2$DEPLEVEL)
summary(covidRegressionBB2)

covidRegressionCC2 <- glm(CC2Subset ~ RANDS.COVID2$ANXFREQ + RANDS.COVID2$ANXLEVEL + RANDS.COVID2$DEPFREQ + RANDS.COVID2$DEPLEVEL)
summary(covidRegressionCC2)

covidRegressionDD2 <- glm(DD2Subset ~ RANDS.COVID2$ANXFREQ + RANDS.COVID2$ANXLEVEL + RANDS.COVID2$DEPFREQ + RANDS.COVID2$DEPLEVEL)
summary(covidRegressionDD2)


# Save the dataset to an .Rdata RANDS1
save(RANDS1, file  = "cleaned_dataset_RANDS1.Rdata")
save(atp, file = "cleaned_dataset_atp.Rdata")
save(atp2, file = "cleaned_dataset_atp2.Rdata")
save(RANDS.COVID1, file = "cleaned_dataset_RANDS_COVID_1.Rdata")
save(RANDS.COVID2, file = "cleaned_dataset_RANDS_COVID_2.Rdata")
save(RANDS2, file = "cleaned_dataset_RANDS2.Rdata")




